# Generated by Django 4.1.7 on 2023-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_job', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('vacancy_title', models.CharField(blank=True, max_length=70, null=True)),
                ('vacancy_org', models.CharField(blank=True, max_length=70, null=True)),
                ('experience', models.CharField(blank=True, max_length=75, null=True)),
                ('candidates', models.CharField(blank=True, max_length=50, null=True)),
                ('date_publish', models.CharField(blank=True, max_length=75, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('researched_topic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=15000)),
            ],
            options={
                'db_table': 'job_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobStandby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_job', models.CharField(max_length=500, unique=True)),
                ('used_term', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'job_standby',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_info', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'db_table': 'path_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scheduler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedulerschema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_path', models.IntegerField(blank=True, null=True)),
                ('tested_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedulerSchema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_scrap', models.CharField(max_length=20, unique=True)),
                ('site_scrap', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'set_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TecnologiesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologie', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tecnologies_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_search', models.CharField(max_length=50, unique=True)),
                ('topic_classification', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'topic_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_job', models.CharField(max_length=400)),
                ('scraped_at', models.DateField()),
            ],
            options={
                'db_table': 'url_test',
                'managed': False,
            },
        ),
    ]
