# Generated by Django 4.1.7 on 2023-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologie', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '"webserver"."preferences"',
                'managed': False,
            },
        ),
    ]
