# Generated by Django 4.1.7 on 2023-03-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_preferencesuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preferencesuser',
            table='preferences',
        ),
    ]
